# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cathegory', '0003_auto_20180603_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='starter',
        ),
        migrations.AddField(
            model_name='post',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='cathegory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='cathegory.Cathegory'),
        ),
    ]
