# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cathegory', '0005_auto_20180612_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cathegory',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='creater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='creater',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
