# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathegory', '0007_topic_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updater',
        ),
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=4000),
        ),
    ]
